#!/usr/bin/env bash
#
# Writes wrangler.generated.toml, which is what every wrangler command uses.
#
# The D1 database id and account id identify resources in a Cloudflare account,
# so they stay out of a public repository. They live in worker/.env (gitignored)
# or in the environment, and are substituted in here at deploy time. Wrangler
# does not interpolate environment variables in its config itself -- it passes
# "$D1_DATABASE_ID" through verbatim -- so this does it.
#
set -euo pipefail

cd "$(dirname "$0")/.."

# shellcheck disable=SC1091
[ -f .env ] && . ./.env

if [ -z "${D1_DATABASE_ID:-}" ]; then
  cat >&2 <<'MISSING'
D1_DATABASE_ID is not set.

Put it in worker/.env (which is gitignored):

    D1_DATABASE_ID=<the uuid from `npx wrangler d1 list`>

or export it. See worker/.env.example.
MISSING
  exit 1
fi

D1_DATABASE_ID="$D1_DATABASE_ID" node -e '
  const fs = require("fs");
  const template = fs.readFileSync("wrangler.toml", "utf8");
  const generated = template.replace(
    /^database_id = .*$/m,
    `database_id = "${process.env.D1_DATABASE_ID}"`,
  );
  if (generated === template) {
    console.error("config.sh: no database_id line found in wrangler.toml");
    process.exit(1);
  }
  fs.writeFileSync(
    "wrangler.generated.toml",
    `# Generated by scripts/config.sh -- do not edit, do not commit.\n${generated}`,
  );
'
echo "Wrote wrangler.generated.toml"
